-- ============================================================================
-- ddl_logging.sql
-- ----------------------------------------------------------------------------
-- Table used by the Logging module (logging_module/etl_logger.py) to persist
-- job-level AND task-level status events.
--
-- One row is written:
--   * when a JOB starts / ends            (task_id IS NULL, log_level='JOB')
--   * when each TASK starts / ends        (task_id IS NOT NULL, log_level='TASK')

-- ============================================================================

CREATE TABLE metadata.etl_job_log (
    log_id BIGINT COMMENT 'Unique log identifier generated by the ETL framework',
    job_id STRING NOT NULL COMMENT 'Unique job run identifier (UUID or scheduler run ID)',
    job_name STRING NOT NULL COMMENT 'Pipeline or job name',
    task_id STRING COMMENT 'Task identifier; NULL for job-level logs',
    task_name STRING COMMENT 'Task name (e.g. Extract_Sales_Data)',
    log_level STRING NOT NULL COMMENT 'JOB or TASK',
    status STRING NOT NULL COMMENT 'STARTED, RUNNING, SUCCESS, FAILED, WARNING',
    start_time TIMESTAMP NOT NULL COMMENT 'Execution start time',
    end_time TIMESTAMP COMMENT 'Execution end time',
    duration_seconds DECIMAL(18,3) COMMENT 'Execution duration in seconds',
    rows_processed BIGINT COMMENT 'Number of rows processed',
    failure_reason STRING COMMENT 'Short error message',
    error_traceback STRING COMMENT 'Complete exception stack trace',
    host_name STRING COMMENT 'Server or container hostname',
    log_file_path STRING COMMENT 'Location of the detailed log file',
    created_at TIMESTAMP COMMENT 'Log creation timestamp'
)
USING iceberg
PARTITIONED BY (days(created_at))
COMMENT 'Audit log of every ETL notification (email) attempt, sent or failed'
TBLPROPERTIES (
    'write.format.default'   = 'parquet',
    'format-version'         = '2'
);



